// Mocks generated by Mockito 5.4.3 from annotations
// in poke_list/test/pokemons_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_list/models/pokemon_details_model.dart' as _i3;
import 'package:poke_list/models/pokemon_list_fragment_model.dart' as _i2;
import 'package:poke_list/services/pokemon_services.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonListFragmentModel_0 extends _i1.SmartFake
    implements _i2.PokemonListFragmentModel {
  _FakePokemonListFragmentModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonDetailsModel_1 extends _i1.SmartFake
    implements _i3.PokemonDetailsModel {
  _FakePokemonDetailsModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonServices extends _i1.Mock implements _i4.PokemonServices {
  @override
  _i5.Future<_i2.PokemonListFragmentModel> getlistFragment({String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getlistFragment,
          [],
          {#url: url},
        ),
        returnValue: _i5.Future<_i2.PokemonListFragmentModel>.value(
            _FakePokemonListFragmentModel_0(
          this,
          Invocation.method(
            #getlistFragment,
            [],
            {#url: url},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.PokemonListFragmentModel>.value(
                _FakePokemonListFragmentModel_0(
          this,
          Invocation.method(
            #getlistFragment,
            [],
            {#url: url},
          ),
        )),
      ) as _i5.Future<_i2.PokemonListFragmentModel>);

  @override
  _i5.Future<_i3.PokemonDetailsModel> getDetails({required String? url}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [],
          {#url: url},
        ),
        returnValue: _i5.Future<_i3.PokemonDetailsModel>.value(
            _FakePokemonDetailsModel_1(
          this,
          Invocation.method(
            #getDetails,
            [],
            {#url: url},
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.PokemonDetailsModel>.value(
            _FakePokemonDetailsModel_1(
          this,
          Invocation.method(
            #getDetails,
            [],
            {#url: url},
          ),
        )),
      ) as _i5.Future<_i3.PokemonDetailsModel>);
}
